theme: minima

title: Edd Armitage - Software Engineer
description: The personal website of a software engineer
author: Edd Armitage

show_excerpts: true

github_username: eddarmitage
linkedin_username: eddarmitage
rss: rss

header_pages:
  - about.md
  - archive.md

exclude:
  - .gitignore
  - README.md
  - LICENSE.md