theme: minima

title: Edd Armitage - Software Engineer
description: The personal website of a software engineer
author: Edd Armitage

github_username: eddarmitage
linkedin_username: eddarmitage
rss: rss

header_pages:
  - _pages/about.md
  - _pages/archive.md

exclude:
  - .gitignore
  - README.md
  - LICENSE