theme: minima

title: Edd Armitage - Software Engineer
description: Personal website of a software engineer
author: Edd Armitage

github_username: eddarmitage
linkedin_username: eddarmitage
rss: rss

header_pages:
  - frontpage.md
  - about.md
  - archive.md

exclude:
  - .gitignore
  - README.md
  - LICENSE